googleAnalytics = "G-P6Z47KPY1C"
baseURL = "/"
languageCode = "lt"
theme = "hugo-winston-theme"
themesDir = "themes"
title = "Verslo Brizas"
paginate = 3
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[languages]
  [Languages.lt]
    languageName = "Lithuanian"
    languageCode = "lt"
    weight = 1
  [Languages.en]
    languageName = "English"
    languageCode = "en"
    weight = 2


[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  google_analytics_id = "G-P6Z47KPY1C"
  twitter_handle = "@verslobrizas"
  showAuthorOnHomepage = true
  showAuthorOnPosts = false
  showPostsOnHomepage = false
  addDot = true
  addFrame = true
  highlightColor = '#33ab20'
  baseColor = "#000005"
  baseOffsetColor = "white"
  headingColor = "white"
  textColor = "white"
  dotColor = "#4ccc14"

# markdown config settings https://gohugo.io/getting-started/configuration-markup/#goldmark
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'Pagrindinis'
    url = '/'
    weight = 1
  [[menu.main]]
    name = "Istorijos"
    identifier = "tags"
    weight = 300
    url = "/tags/"
